import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { ToastProvider } from "@/components/molecules/toast-provider";
import "./globals.css";
const instrumentalSans = Instrument_Sans({ subsets: ["latin"] });

import LayoutWrapper from "@/components/atoms/layout-wrapper";
export const metadata: Metadata = {
  title: "Links Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutWrapper>
      <html lang="en">
        <body className={`${instrumentalSans.className}   bg-light-grey`}>
          <ToastProvider>{children}</ToastProvider>
          {/* {children} */}
        </body>
      </html>
    </LayoutWrapper>
  );
}
